### ISSUE TITLE
Exception: "AttributeError('peripheral_compartments')"

### ISSUE THREAD

**Issue by schaedeli** [pharmpy/pharmr#117]
Hi, 
I have been running a modelsearch using `run_modelsearch()` tool in R, running on improve, and I am facing the following error, leading to stop of the modelsearch. Initial candidate models without peripherals were generated and run, then the first model code with PERIPHERALS(1) was generated but not run, (or maybe started somewhere in the background) then, apparently the run crashed.
Does this error message look familiar to you?
Thanks, Franziska

```
sp1 <- "ABSORPTION([ZO,SEQ-ZO-FO]);TRANSITS([1,3],*);PERIPHERALS(1..2);ELIMINATION([MM,MIX-FO-MM])"
res_modelsearch <- 
  run_modelsearch(search_space=sp1,
                  algorithm='reduced_stepwise',
                  model=input_model,
                  iiv_strategy='absorption_delay')
```

failed with Error:

Future exception was never retrieved
future: <Future finished exception=TimeoutError('Timeout')>
tornado.util.TimeoutError: Timeout
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:22: UserWarning: modelsearch_candidate43: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:22: UserWarning: modelsearch_candidate44: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:22: UserWarning: modelsearch_candidate45: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:22: UserWarning: modelsearch_candidate42: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:22: UserWarning: modelsearch_candidate46: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:22: UserWarning: modelsearch_candidate47: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:22: UserWarning: modelsearch_candidate17: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:22: UserWarning: modelsearch_candidate22: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
2022-09-22 19:39:33,600 - distributed.worker - WARNING - Compute Failed
**Key:       PERIPHERALS(1)-add_iivs-copy-update_inits-run0-c2809e2e-4668-4f3c-b05d-c6ac5ee79413
Function:  execute_task
args:      ((<function retrieve_from_database_or_execute_model_with_tool.<locals>.task at 0x7fd6b76b3790>, (<function _add_iiv_to_func at 0x7fd6b76af8b0>, 'absorption_delay', (<function _apply_transformation at 0x7fd6b76af670>, ('PERIPHERALS', 1), functools.partial(<function set_peripheral_compartments at 0x7fd6ffd448b0>, n=1), (<function update_initial_estimates at 0x7fd6b6b76ca0>, (<function _copy at 0x7fd6b76af820>, 'modelsearch_candidate22', (('PERIPHERALS', 1),), <Pharmpy model object modelsearch_candidate3>))))))
kwargs:    {}
Exception: "AttributeError('peripheral_compartments')"**

<Client: 'inproc://172.17.0.23/335/10' processes=1 threads=12, memory=31.24 GiB>
AttributeError: peripheral_compartments
Full stack:
AttributeErrorperipheral_compartmentsc("  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/wrap.py\", line 46, in _func\n    return run_tool(tool_name, *args, **kwargs)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py\", line 170, in run_tool\n    res = execute_workflow(wf, dispatcher=dispatcher, database=database)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/execute.py\", line 58, in execute_workflow\n    res = dispatcher.run(workflow)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/dispatchers/local_dask.py\", line 40, in run\n    res = client.get(dsk_optimized, 'results')\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 3052, in get\n    results = self.gather(packed, asynchronous=asynchronous, direct=direct)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 2226, in gather\n    return self.sync(\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 338, in sync\n    return sync(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 405, in sync\n    raise exc.with_traceback(tb)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 378, in f\n    result = yield future\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/tornado/gen.py\", line 762, in run\n    value = future.result()\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 2089, in _gather\n    raise exception.with_traceback(traceback)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/modelsearch/algorithms.py\", line 222, in _apply_transformation\n    func(model)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/modeling/odes.py\", line 1289, in set_peripheral_compartments\n    per = len(model.statements.ode_system.peripheral_compartments)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/model/statements.py\", line 189, in __getattr__\n    raise AttributeError(key)\n")Traceback (most recent call last):
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/wrap.py", line 46, in _func
    return run_tool(tool_name, *args, **kwargs)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py", line 170, in run_tool
    res = execute_workflow(wf, dispatcher=dispatcher, database=database)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/execute.py", line 58, in execute_workflow
    res = dispatcher.run(workflow)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/dispatchers/local_dask.py", line 40, in run
    res = client.get(dsk_optimized, 'results')
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 3052, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 2226, in gather
    return self.sync(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 338, in sync
    return sync(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 405, in sync
    raise exc.with_traceback(tb)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 378, in f
    result = yield future
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 2089, in _gather
    raise exception.with_traceback(traceback)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/modelsearch/algorithms.py", line 222, in _apply_transformation
    func(model)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/modeling/odes.py", line 1289, in set_peripheral_compartments
    per = len(model.statements.ode_system.peripheral_compartments)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/model/statements.py", line 189, in __getattr__
    raise AttributeError(key)
AttributeError: peripheral_compartments

pharmr version: 0.76.5
'0.76.5'
Pharmpy version: 0.76.5

**Comment by stellabelin** [comment]
Hi! Yes, it was fixed in [ebfafb45faddefb287b6e43cff1501197d496428](https://github.com/pharmpy/pharmpy/commit/ebfafb45faddefb287b6e43cff1501197d496428), if you use Pharmpy 0.78.0 it should work!

**Comment by schaedeli** [comment]
thanks. It looks like PharmPy 0.76 is still running on our environment. But interestingly, this error occurred in one case but not in the other that was run on the same day with the same installation

**Comment by stellabelin** [comment]
Interesting, with the same search space/input model? Also, when you have a chance to test with Pharmpy 0.78.0, let us know if it works!

**Comment by stellabelin** [comment]
Hi! @schaedeli, can this issue be closed?

**Comment by schaedeli** [comment]
Hi Stella
thanks for reaching out. This specific error did not occur to me anymore, however, when running the amd tool, an error occurs that looks a bit similar:
```
# 2022-11-04 16:15:21,500 - distributed.worker - WARNING - Compute Failed
# Key:       PERIPHERALS(1)-add_iivs-choose_best_model-copy-update_inits-run0-073758b1-010c-4963-b66b-1ca76085cb55
# Function:  execute_task
# args:      ((<function retrieve_from_database_or_execute_model_with_tool.<locals>.task at 0x7f7cb16a84c0>, <pharmpy.workflows.tool_database.local_directory.LocalDirectoryToolDatabase object at 0x7f7cb18bfca0>, (<function _add_iiv_to_func at 0x7f7cb0ea3670>, 'absorption_delay', (<function _apply_transformation at 0x7f7cb0ea3430>, ('PERIPHERALS', 1), functools.partial(<function set_peripheral_compartments at 0x7f7d0c00ab80>, n=1), (<function update_initial_estimates at 0x7f7cb313a040>, (<function _copy at 0x7f7cb0ea35e0>, 'modelsearch_run84', (('PERIPHERALS', 1),), (<function _get_best_model at 0x7f7cb0ea31f0>, <Pharmpy model object modelsearch_run18>, <Pharmpy model object modelsearch_run31>)))))))
# kwargs:    {}
# Exception: "TypeError('Cannot convert expression to float')"
# Pharmpy version: 0.83.0

```

(I'm not sure if this is the same dataset, I think it is a different one, but also oral absorption and 2-cmt distribution in the original model)

Do you think this should be handled under the same issue or a new issue needs to be opened?

I am also happy to copy the full error stack, just let me know.

Kind Regards
Franziska
