### ISSUE TITLE
Parent-metabolite modeling -v0.107 "Metabolite is not JSON serializable"

### ISSUE THREAD

**Issue by SylvieRetout** [pharmpy/pharmr#156]
Hi All,

I am facing an issue with the modeling of a parent-metabolite dataset using pharmr v0.107. 
Please see the code I use below. The tool stops after the modeling of the parent data with the following error message: "Object of type Metabolite is not JSON serializable" (see more below)

dataset_path <- "dataset_filtered4.csv"

sp <- "ABSORPTION([FO,SEQ-ZO-FO]);ELIMINATION(FO);LAGTIME([OFF,ON]);PERIPHERALS([0,1]);TRANSITS([0,1,3],*);METABOLITE([PSC, BASIC]);PERIPHERALS([0,1], MET)"

res = run_amd(dataset_path,
              search_space=sp,
              modeltype = "drug_metabolite", 
              administration="oral", 
              # order=order, 
              cl_init=1, vc_init=3.0, mat_init=0.1)

<img width="907" alt="image" src="https://github.com/pharmpy/pharmr/assets/78366723/b9dc5d0c-6f22-4fb7-9a30-4930644b0b53">
2
Thanks for your help,
Sylvie

**Comment by stellabelin** [comment]
This should be fixed in 0.108.0, closing the issue.
