### ISSUE TITLE
pharmr documention

### ISSUE THREAD

**Issue by emiliesg** [pharmpy/pharmr#16]
Could documentation for pharmr be provided in R language? Currently the section dedicated to Pharmpy in R mostly specifies how to rewrite Pharmpy functions in R, but all the rest of the documentation is provided in Python language. This will likely be a challenge for new users using R who are not familiar with python/reticulate. Some things are currently somewhat unclear. For example, for reading a model, are read_model() and pharmpy$Model() the same.  Another example, modelfit_results can be used to access elements from this object (model$modelfit_results$parameter_estimates), but also apply functions (model$modelfit_results$eta_shrinkage()), and a clearer list of object elements vs functions would be helpful to have.

**Comment by stellabelin** [comment]
Hi! Thank you for your comment and the suggestion! We are working on updating the documentation and function names for clarity, which will hopefully make it easier to use.

**Comment by pharmpy-dev-123** [comment]
I think the general idea of having documentation in R has been addressed. More specific concerns should be raised in new issues. Closing this one.
