### ISSUE TITLE
many problems with run_modelsearch 

### ISSUE THREAD

**Issue by artikandms** [pharmpy/pharmr#160]
I struggle with run_modelsearch, when I try to run the function, I can only test absorption types, and only one at a time. For everything else, I always get this error message. I don’t know if it’s from my code, python, or pharmr.
<img width="506" alt="image" src="https://github.com/pharmpy/pharmr/assets/166139814/dfdf936d-f84a-4af7-addc-6844ed8ef3b3">

**Comment by rikardn** [comment]
How do you call `run_modelsearch`? In particular which search space do you ask for?

**Comment by artikandms** [comment]
for example : 

test2 <- run_modelsearch(search_space = "ABSORPTION(FO) ; ELIMINATION(MM)", 
                       algorithm = "reduced_stepwise",
                       model=firstmodel1,
                       results=modelfitresults,
                       iiv_strategy="no_add",
                       rank_type="bic",
                       strictness = "minimization_successful or (rounding_errors and sigdigs >= 0.1)",
                       cutoff=NULL)

**Comment by artikandms** [comment]
thank you very much for your help, it seems to work properly. As the search space had been incorrectly coded, only the BASE folder was created, so there was no run, which I think explains the error message.
Thank you again for your reactivity and your precious help.

**Comment by rikardn** [comment]
Thanks for the feedback!
