### ISSUE TITLE
problem with predictions, residuals, and plots functions

### ISSUE THREAD

**Issue by artikandms** [pharmpy/pharmr#165]
Hi ! 
I cannot understand what pharmr expects in value of "predictions" or "residuals" in the plot functions. 
For example, I ran my model, I read the results with modelfit. I have a "column"  predictions with PRED and IPRED. However, when I run `plot_dv_vs_pred(model, modelresults$predictions)` , I get the following error message. I also tried to select only PRED, without success.
So I find it hard to understand how to use plot functions with predictions and residuals as arguments. I didn’t find any additional explanations on the user guide. Can you help me please? 

<img width="383" alt="Capture d’écran 2024-04-22 114349" src="https://github.com/pharmpy/pharmr/assets/166139814/f12b8062-1e58-4944-b13f-634cda9b3084">
<img width="286" alt="Capture d’écran 2024-04-22 114436" src="https://github.com/pharmpy/pharmr/assets/166139814/07d2bcdd-b523-445b-87b6-136d024d08fb">

**Comment by rikardn** [comment]
The expected predictions are those coming from a fit. For example:

```
library(pharmr)

model <- read_model("run1.mod")
res <- read_modelfit_results("run1.mod")
plot_dv_vs_pred(model, res$predictions)
```

Currently the predictions has a multiindex which does not work well in R. The next version will change this so that it has a single index being the index of the data record of the original dataset.
