### ISSUE TITLE
documentation example in read_model_from_string

### ISSUE THREAD

**Issue by joaoabr** [pharmpy/pharmr#26]
pharmr version 0.35.1. 
1) there are too many inverted commas in the example
2) it is unclear what the text in _Value_ means in this context

**Comment by rikardn** [comment]
2. It was supposed to mean "the read model object", but I have changed it to something I hope is clearer: pharmpy/pharmpy@43445b629b8fce952ab5106d8fe869c64d6cbc43

**Comment by rikardn** [comment]
1. Is an issue with converting the a multiline string. R supports this so it should be possible to fix. Thanks for reporting!

**Comment by rikardn** [comment]
Fixed with 66f4ab82c28f74e09ef1b7e8e74f5cddcc549206
