### ISSUE TITLE
remove_estimation_step

### ISSUE THREAD

**Issue by SimonBuatois** [pharmpy/pharmr#30]
remove_estimation_step(model, 1) is giving me the following error message: Error in py_call_impl(callable, dots$args, dots$keywords) : 
TypeError: list indices must be integers or slices, not float. In addition, there is a typo in the last line len(ests) instead of length(ests)

relevant for linearization?

**Comment by stellabelin** [comment]
Hi! This was fixed in pharmpy/pharmpy@cf4563054b86aca88787a087113be8dc28db8a96 and should be in the 0.36.0 release of Pharmr/Pharmpy, please let me know if you still get the same error and I'll reopen the issue!
