### ISSUE TITLE
remove_peripheral_compartment

### ISSUE THREAD

**Issue by SimonBuatois** [pharmpy/pharmr#34]
Bug in the display of the inital estimates. set_peripheral_compartments(model, 2) is giving me the following error: Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: 'float' object cannot be interpreted as an integer

align with set_peripheral_compartment

**Comment by stellabelin** [comment]
Yes, this is due to the same as in #39, so the example should work when fixed. Will be in next release.
