### ISSUE TITLE
set_peripheral_compartments

### ISSUE THREAD

**Issue by SimonBuatois** [pharmpy/pharmr#39]
set_peripheral_compartments(model, 2) is giving me the following error: Error in py_call_impl(callable, dots$args, dots$keywords) : TypeError: 'float' object cannot be interpreted as an integer
Does the ADVAN change accordingly as well?

**Comment by stellabelin** [comment]
Same reason as in #30, but I missed changing `set_peripheral_compartments`. Will be in the next release.
