### ISSUE TITLE
Error message with run_tool related to DAtaInfo

### ISSUE THREAD

**Issue by SylvieRetout** [pharmpy/pharmr#64]
Hi, 
For some examples, we have the following error message when running the run_tool function:

"Error in py_call_impl(callable, dots$args, dots$keywords) : 
  AttributeError: 'DataInfo' object has no attribute 'name' "

The code used is: 

sp <- "PERIPHERALS(1..2)"
res_modelsearch <- run_tool("modelsearch", 
+                             model=input_model,
+                             search_space=sp, 
+                             algorithm="reduced_stepwise", 
+                             rankfunc="bic", 
+                             iiv_strategy=3)

The dataset includes the following columns: 
![image](https://user-images.githubusercontent.com/78366723/168641336-b6ca1253-1c97-41e3-ac07-e37a147625cc.png)

Any idea of the issue here?

Thank you,
Kind regards,

Sylvie

**Comment by rikardn** [comment]
Thanks for reporting this. 

Some followup questions: Do you have a `.datainfo` file with your dataset? What does your `$INPUT` look like?

**Comment by rikardn** [comment]
Is it by the way possible to get the full traceback? There should be a "Show traceback" to the right of the error message in R studio.

**Comment by SylvieRetout** [comment]
Here is a more detailed traceback:
![image](https://user-images.githubusercontent.com/78366723/169068810-eeacb7e1-6db7-4fdc-9aa8-33f15355902c.png)

**Comment by stellabelin** [comment]
Hi Sylvie! The bug has now been fixed, the issue is that modelsearch doesn't currently support a CMT column, so it needs to be dropped/removed or specified in the datainfo as dropped before running the tool. The actual bug was in the error message, the error that will be raised after the fix will be something like: 

```
ValueError: Found compartment column ['CMT'] in dataset. This is currently not supported by modelsearch. Please remove or drop this column and try again
```

**Comment by SylvieRetout** [comment]
Thank you Stella.
Kind regards,
Sylvie


-----------------------------------

Sylvie Retout, PhD


Senior Principal Scientist, Clinical Pharmacometrics

Predictive Modeling and Data Analytics

Roche Pharma Research & Early Development
Roche Innovation Center Basel

Institut Roche

4, cours de l’Ile Seguin

92100 Boulogne-Billancourt

Phone: +33 1 47 61 40 36

Mobile: +33 6 73 99 50 65

mailto: ***@***.***

This message and any of the attachments may contain confidential and
proprietary material for the sole use of the intended recipient. Any review
of distribution by others is strictly prohibited. If you are not the
intended recipient please contact the sender and delete all copies.
