### ISSUE TITLE
iivsearch: The title of the $PROBLEM of the base_model, i.e. [VC,CL,QP2,VP2,QP1,VP1] does not correspond to the actual omega structure

### ISSUE THREAD

**Issue by cossonvalerie** [pharmpy/pharmr#77]
Issue with iivsearch (before latest update of PharmPy). I used the following arguments: algorithm= problem brute_force, iiv_strategy=1
The title of the $PROBLEM of the base_model, i.e. [VC,CL,QP2,VP2,QP1,VP1] does not correspond to the actual omega structure. With 6 parameters within [], it should be the block(6).
$PROBLEM [VC,CL,QP2,VP2,QP1,VP1]
$INPUT C ID PT STUD TIME NOMTIME TAD NOMTAD AMT RATE DV EVID BLQ NOMDOSE AGE SEX RACE WT BMI BSA COHORT PART FLAG COMMENT
$DATA C:\Users\Public\ADaMO\Phase_1\Model_1\modelsearch_RUV\iivsearch_dir2\models\.datasets\base_model.csv IGNORE=@
$SUBROUTINES ADVAN11  TRANS4 
$PK
VP2 = THETA(6)*EXP(ETA(4))
QP2 = THETA(5)*EXP(ETA(3))
VP1 = THETA(4)*EXP(ETA(6))
QP1 = THETA(3)*EXP(ETA(5))
VC = THETA(1) * EXP(ETA(1))
CL = THETA(2) * EXP(ETA(2))
(…)
$OMEGA BLOCK(2)
0.0109671	; IIV_VC
0.0193731	; IIV_VC_IIV_CL
0.0933452	; IIV_CL
$OMEGA  0.09 ; IIV_QP2
$OMEGA  0.09 ; IIV_VP2
$OMEGA  0.09 ; IIV_QP1
$OMEGA  0.09 ; IIV_VP1
$SIGMA  0.0566592 ; sigma

In reality, there is a block(2) for CL and VC and the rest is diagonal. Therefore the $PROB title should be [VC,CL]+[QP2]+[VP2]+[QP1]+[VP1].

I would recommend to harmonize the way the $PROB titles are written across iiv strategy (2, 1 or 0), i.e. 
for diagonal [VC]+[CL]+[QP2]+[VP2]+[QP1]+[VP1]  
for block [VC,CL,QP2,VP2,QP1,VP1]

**Comment by stellabelin** [comment]
Hi! Thank you for reporting this! I agree and it has been changed, so in the next release the $PROBLEM will correspond to the current block structure. Previously it was only a representation of parameters with IIV left (since step 1 is selecting which IIV to keep), but of course the [] makes it look like a block.
