### ISSUE TITLE
No results summary after run_modelsearch

### ISSUE THREAD

**Issue by schaedeli** [pharmpy/pharmr#79]
Hi, I run into a problem when using run_modelsearch() with an iv model that I have added to my test models. Not sure it has to do with the model or something else.

```
## -- check different search algorithms -- ##
sp1 <- "PERIPHERALS(1..2)"
sp2 <- "PERIPHERALS(1..2);ELIMINATION(MM)"

# 1 - reduced_stepwise - iiv_strategy=3
# res_modelsearch_1 <- run_tool("modelsearch",
res_modelsearch_1 <- run_modelsearch( 
                            model=input_model,
                            search_space=sp1, 
#                            search_space=sp2, 
                            algorithm="reduced_stepwise", 
                            rankfunc="bic", 
                            iiv_strategy='no_add')
```

This returns an error message (see below) and does not produce the results file. However, the two candidate model directory tree and models were produced and ran successfully. Is this a known issue?

```
distributed.worker - WARNING - Compute Failed
Function:  post_process
args:      ('bic', None, <Pharmpy model object run1>, <Pharmpy model object modelsearch_candidate1>, <Pharmpy model object modelsearch_candidate2>)
kwargs:    {}
Exception: ValueError('Length of values (65) does not match length of index (58)')

 Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: Length of values (65) does not match length of index (58) 
```

**Comment by stellabelin** [comment]
Hi! Thanks for reporting! This is not a known issue, and I could not recreate it. Could you try rerunning this example? There has been some changes to how the results are generated which could affect. Could you also add the following to the code you're running at the end of your script: 

```
reticulate::py_last_error()
```

And then write the output here? This makes it easier to track where the error occurs.

**Comment by schaedeli** [comment]
Hi
I have not been able to reproduce that specific error, so I think this issue can be closed.

**Comment by stellabelin** [comment]
Hi! Thank you for testing! Closing the issue.
