### ISSUE TITLE
Handle integers in options

### ISSUE THREAD

**Issue by stellabelin** [pharmpy/pharmr#80]
Currently, they will be handled as `double`-type which causes issues. Could be solved by having an integer-conversion in relevant wrapper functions.

**Comment by rikardn** [comment]
Could this be done generally on the R side? I think we have it on the Python side in some cases, but it is mostly needed in R.

Some function that if will pass on an integer (`16L`), convert an integer-like float to int and give error for non-integer floats

**Comment by stellabelin** [comment]
I was thinking that we could detect the type when there's a default (either typing or checking for `.`), but if there is no default I guess we need on the Pharmpy side to allow both?

**Comment by rikardn** [comment]
For the functions in `pharmpy.modeling` we know the type from the docstring. If integer we can call the conversion function.

**Comment by pharmpy-dev-123** [comment]
Given the amount of issues raised by modelers around this problem I think we should start with adding a paragraph about this situation in the documentation, including the known `...L` workaround, as @stellabelin suggested earlier. Until we find a better solution.

**Comment by stellabelin** [comment]
We now have a paragraph in the documentation about this [here](https://pharmpy.github.io/latest/using_r.html#floats-and-integers) and the `list()` vs `c()` issue [here](https://pharmpy.github.io/latest/using_r.html#floats-and-integers).

**Comment by stellabelin** [comment]
This will be fixed successively by using typing (we can check if arg should be an `int` and convert if needed)

**Comment by stellabelin** [comment]
Also will fix issues where the default for an option is `int` (see `run_ruvsearch`). Currently, Pharmpy will raise because it's a float, even if the user hasn't inputted anything.

**Comment by rikardn** [comment]
This has been fixed in the automatic wrapper functions
