### ISSUE TITLE
update initial estimates using Parameter()?

### ISSUE THREAD

**Issue by joaoabr** [pharmpy/pharmr#92]
I am trying to update the initial estimates of some parameters (model$parameters), but I am struggling to do so. In the documentation "Model parameters", point me towards an example in R using Parameter(), but I do not seem to find this in R. 

If I have candidate6$parameters, giving me:
                       value lower     upper    fix
THETA(1)    3.882510   0.0   1000000  False
THETA(2)    0.024234   0.0   1000000  False
THETA(3)    0.012237   0.0  999999.0  False
THETA(4)    5.252300   0.0  999999.0  False

How can I update the value of THETA(1) in R?

**Comment by pharmpy-dev-123** [comment]
The API for parameters was changed recently. I'll have a look at it and come back to you.

**Comment by SCarter79** [comment]
`set_initial_estimates(model, list('THETA(1)'=2)) ` - if you get stuck in Rstudio you can just highlight the function and press F1

**Comment by joaoabr** [comment]
Thanks! Would it make sense to add this example in R to the userguide? (https://pharmpy.github.io/latest/model.html#modelfit-results)

**Comment by stellabelin** [comment]
I think it makes sense to clarify how to set initial estimates. Currently, the `modelfit_results` and `model` documentation is outdated and will be getting an update as part of the changes for Pharmpy 1.0. The `modeling` user guide will have an example on this type of change. Closing this issue!
