### ISSUE TITLE
Fail to output the final selected model file

### ISSUE THREAD

**Issue by liuxl17** [pharmpy/pharmr#95]
The results from each module were summarized in the results.csv/.json file. I think there is supposed to be a `.mod` file integrating all the best models from each module to become a final model. While the "models" folder in the "amd_dir#" directory was empty when the final model was generated.
The warning message is:
```
Warning message:
In max(.) : no non-missing arguments to max; returning -Inf
Model search results are in the folder of modelsearch_dir-Inf
Error in saveRDS(x, con, version = version, refhook = refhook, ascii = text) : 
  cannot open the connection
Calls: write_rds -> saveRDS
In addition: Warning message:
In saveRDS(x, con, version = version, refhook = refhook, ascii = text) :
  cannot open file 'modelsearch_dir-Inf/modelsearch_summary': No such file or directory
Execution halted
```

**Comment by pharmpy-dev-123** [comment]
Did you make progress on this one @liuxl17 ? I remember we discussed this last week.

**Comment by liuxl17** [comment]
Yes, the warning message is unrelated to the AMD tool and was fixed now. 

The issue is that the `models` folder under the `amd_dir` directory was empty when the execution finished. I suppose that folder is used as a temporary folder to put the model candidate files generated during the running process and once the model is established, the files will be moved into a new folder named by the model candidate. That's why the `model` folder is empty when the model development is done. Maybe we could put the final selected model files (i.e., the best covsearch model) into that folder or just delete that folder when the running is finished?

**Comment by stellabelin** [comment]
Hi! There is now an issue in the Pharmpy repo which includes adding a directory (also for each subtool) with only the final model (named final_model). The issue can be found here: https://github.com/pharmpy/pharmpy/issues/1054. Closing this issue.
