### ISSUE TITLE
rank in modelsearch results

### ISSUE THREAD

**Issue by joaoabr** [pharmpy/pharmr#99]
The rank order in the summary_tool of a run_modelsearch() does not seem to follow the bic values. Have you seen this before?

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/abrantj1/AppData/Local/Temp/12/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/abrantj1/AppData/Local/Temp/12/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

summary_tool |   |   |   |   |  
-- | -- | -- | -- | -- | --
model | description | dbic | bic | rank | parent_model
modelsearch_candidate5 | PERIPHERALS(1);PERIPHERALS(2) | 598.1661 | 145.7152 | 3 | modelsearch_candidate2
modelsearch_candidate8 | PERIPHERALS(1);PERIPHERALS(2);ELIMINATION(MM) | 592.4984 | 151.383 | 6 | modelsearch_candidate5
modelsearch_candidate7 | PERIPHERALS(1);ELIMINATION(MM);PERIPHERALS(2) | 592.4984 | 151.383 | 7 | modelsearch_candidate4
modelsearch_candidate2 | PERIPHERALS(1) | 530.1581 | 213.7233 | 1 | run1
modelsearch_candidate4 | PERIPHERALS(1);ELIMINATION(MM) | 523.6491 | 220.2323 | 4 | modelsearch_candidate2
run1 |   | 0 | 743.8814 | 8 | run1
modelsearch_candidate1 | ELIMINATION(MM) | -8.34555 | 752.2269 | 9 | run1
modelsearch_candidate3 | ELIMINATION(MM);PERIPHERALS(1) |   |   | 2 | modelsearch_candidate1
modelsearch_candidate6 | ELIMINATION(MM);PERIPHERALS(1);PERIPHERALS(2) |   |   | 5 | modelsearch_candidate3

</body>

</html>

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/abrantj1/AppData/Local/Temp/12/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/abrantj1/AppData/Local/Temp/12/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

summary_models |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
model | description | minimization_successful | errors_found | warnings_found | ofv | aic | bic | runtime_total | estimation_runtime
modelsearch_candidate5 | PERIPHERALS(1);PERIPHERALS(2) | TRUE | 0 | 0 | 101.5333788 | 121.5334 | 145.7152 |   | 5.77
modelsearch_candidate8 | PERIPHERALS(1);PERIPHERALS(2);ELIMINATION(MM) | TRUE | 0 | 0 | 101.360442 | 123.3604 | 151.383 |   | 43.68
modelsearch_candidate7 | PERIPHERALS(1);ELIMINATION(MM);PERIPHERALS(2) | TRUE | 0 | 0 | 101.3604426 | 123.3604 | 151.383 |   | 58.3
modelsearch_candidate2 | PERIPHERALS(1) | TRUE | 0 | 0 | 181.2227051 | 197.2227 | 213.7233 |   | 2.1
modelsearch_candidate4 | PERIPHERALS(1);ELIMINATION(MM) | TRUE | 0 | 1 | 181.8910676 | 199.8911 | 220.2323 |   | 18.97
run1 |   | TRUE | 0 | 0 | 723.0620825 | 735.0621 | 743.8814 |   | 1.6
modelsearch_candidate1 | ELIMINATION(MM) | TRUE | 0 | 1 | 725.5669931 | 739.567 | 752.2269 |   | 18.01
modelsearch_candidate3 | ELIMINATION(MM);PERIPHERALS(1) | FALSE | 4 | 0 |   |   |   |   | 0.01
modelsearch_candidate6 | ELIMINATION(MM);PERIPHERALS(1);PERIPHERALS(2) | FALSE | 4 | 0 |   |   |   |   | 0.01

</body>

</html>

**Comment by stellabelin** [comment]
Hi! Thanks for reporting! Yes, it was brought up this week and has been fixed in pharmpy/pharmpy@26ff49b83cc486eafa47dd6b89190130743e0e98. The bug appeared  when there were missing values for the OFV etc. The fix will be in the next release!
